export const SOURCE_ROUTE_MAP = {
  '/': 'src/pages/index.html',
  '/index.html': 'src/pages/index.html',
  '/products': 'src/pages/products.html',
  '/products.html': 'src/pages/products.html',
  '/product': 'src/pages/product.html',
  '/product.html': 'src/pages/product.html',
  '/cart': 'src/pages/cart.html',
  '/cart.html': 'src/pages/cart.html',
  '/checkout': 'src/pages/checkout.html',
  '/checkout.html': 'src/pages/checkout.html',
  '/order-confirmation': 'src/pages/order-confirmation.html',
  '/order-confirmation.html': 'src/pages/order-confirmation.html',
  '/offline': 'src/pages/offline.html',
  '/offline.html': 'src/pages/offline.html',
  '/admin/login': 'src/pages/admin/login.html',
  '/admin/login.html': 'src/pages/admin/login.html',
  '/admin/dashboard': 'src/pages/admin/dashboard.html',
  '/admin/dashboard.html': 'src/pages/admin/dashboard.html',
  '/admin/products': 'src/pages/admin/products.html',
  '/admin/products.html': 'src/pages/admin/products.html',
  '/admin/product-edit': 'src/pages/admin/product-edit.html',
  '/admin/product-edit.html': 'src/pages/admin/product-edit.html',
  '/admin/categories': 'src/pages/admin/categories.html',
  '/admin/categories.html': 'src/pages/admin/categories.html'
};

export const DIST_ROUTE_MAP = {
  '/': 'dist/index.html',
  '/index.html': 'dist/index.html',
  '/products': 'dist/products.html',
  '/products.html': 'dist/products.html',
  '/product': 'dist/product.html',
  '/product.html': 'dist/product.html',
  '/cart': 'dist/cart.html',
  '/cart.html': 'dist/cart.html',
  '/checkout': 'dist/checkout.html',
  '/checkout.html': 'dist/checkout.html',
  '/order-confirmation': 'dist/order-confirmation.html',
  '/order-confirmation.html': 'dist/order-confirmation.html',
  '/offline': 'dist/offline.html',
  '/offline.html': 'dist/offline.html',
  '/admin/login': 'dist/admin/login.html',
  '/admin/login.html': 'dist/admin/login.html',
  '/admin/dashboard': 'dist/admin/dashboard.html',
  '/admin/dashboard.html': 'dist/admin/dashboard.html',
  '/admin/products': 'dist/admin/products.html',
  '/admin/products.html': 'dist/admin/products.html',
  '/admin/product-edit': 'dist/admin/product-edit.html',
  '/admin/product-edit.html': 'dist/admin/product-edit.html',
  '/admin/categories': 'dist/admin/categories.html',
  '/admin/categories.html': 'dist/admin/categories.html'
};
